#pragma once

// TODO (daniel): Render defines.

#define VOIDSTORM_PROFILE_NUM_COUNTERS 25

#define VOIDSTORM_APPLICATION_HEAP_SIZE Megabytes(80)
#define VOIDSTORM_RENDER_HEAP_SIZE Megabytes(16)

#define VOIDSTORM_APPLICATION_PERMANENT_STACK_SIZE Megabytes(60)
#define VOIDSTORM_APPLICATION_WORLD_STACK_SIZE Megabytes(100)
#define VOIDSTORM_APPLICATION_TRANSIENT_STACK_SIZE Megabytes(0)

#define VOIDSTORM_SCRIPT_ELEMENT_SIZE 40
#define VOIDSTORM_SCRIPT_ELEMENT_COUNT (1 << 16) // 65 536

#define VOIDSTORM_ENTITY_MAX_COUNT (1 << 12) // 4096

#define VOIDSTORM_TRANSFORM_COMPONENT_COUNT (1 << 12) 
#define VOIDSTORM_PHYSICS_COMPONENT_COUNT (1 << 12)
#define VOIDSTORM_COLLISION_COMPONENT_COUNT (1 << 12)
#define VOIDSTORM_RESPONDER_COMPONENT_COUNT (1 << 12)
#define VOIDSTORM_SPRITE_COMPONENT_COUNT (1 << 12)

#define VOIDSTORM_DEBUG_SPRITE_BOUNDS 0 // RED
#define VOIDSTORM_DEBUG_COLLISION_BOUNDS 0 // BLUE
#define VOIDSTORM_DEBUG_PROXY_BOUNDS 0  // GREEN
