#pragma once

// TODO: Render defines.

#define VOIDSTORM_ENTITY_MAX_COUNT (1 << 12) // 4096

#define VOIDSTORM_TRANSFORM_COMPONENT_COUNT (1 << 12) 
#define VOIDSTORM_PHYSICS_COMPONENT_COUNT (1 << 12)
#define VOIDSTORM_COLLISION_COMPONENT_COUNT (1 << 12)
#define VOIDSTORM_RESPONDER_COMPONENT_COUNT (1 << 12)
#define VOIDSTORM_SPRITE_COMPONENT_COUNT (1 << 12)

#define VOIDSTORM_PROFILE_NUM_COUNTERS 25

#define VOIDSTORM_APPLICATION_HEAP_SIZE Megabytes(20)
#define VOIDSTORM_RENDER_HEAP_SIZE Megabytes(5)

#define VOIDSTORM_APPLICATION_PERMANENT_STACK_SIZE Megabytes(40)
#define VOIDSTORM_APPLICATION_TRANSIENT_STACK_SIZE Megabytes(40)

#define VOIDSTORM_SCRIPT_ELEMENT_SIZE 40
#define VOIDSTORM_SCRIPT_ELEMENT_COUNT (1 << 13) // 8192
